

DROP TABLE TAREA_DEPENDENCIA;
DROP TABLE TAREA_ESTUDIANTE;
DROP TABLE TABLERO_PROFESOR;
DROP TABLE TAREA;
DROP TABLE ESTADO;
DROP TABLE TABLERO;
DROP TABLE PROFESOR;
DROP TABLE ESTUDIANTE_AMIGO;
DROP TABLE ESTUDIANTE_TABLERO;
DROP TABLE ESTUDIANTE;
